Part12
dniman/test_guru pull request #11
Opened 2019-02-15 13:23 UTC by dniman

2019-02-15 17:43 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
>      @test = Test.new(test_params)
`current_user.created_tests.new(test_params)`

2019-02-15 17:43 UTC, BubuntuClu commented on ~
> +class SessionsController < Devise::SessionsController
что-то лишнее закралось

2019-02-15 17:43 UTC, BubuntuClu commented
`3. Сделайте так чтобы по умолчанию URL параметр языка не добавлялся в том случае когда установленная локаль такая же как локаль по умолчанию` а это где?

2019-02-15 19:08 UTC, psylone requested changes
Отсутствует 3-е задние.

2019-02-16 08:06 UTC, dniman commented on ~
> +class SessionsController < Devise::SessionsController
не совсем понятно что именно...
А есть другой способ, чтобы передать в set_flash_message хэш-параметр?

2019-02-16 08:44 UTC, BubuntuClu commented on ~
> +class SessionsController < Devise::SessionsController
я про то, что файл с именем `~`. может во время дебага что-то нажал и он создался или что-то еще. у тебя ведь есть `session_controller.rb` в репозитории

2019-02-16 08:44 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def default_url_options(options={ lang: I18n.locale })
а если тебе передали локаль языка, который не поддерживается у тебя в приложении?

либо в этом же метода, или в `before_action` лучше проверить это. там же ты сможешь установить сразу установить локаль, а тут у тебя просто останется сделать 

```
def default_url_options
   I18n.locale == I18n.default_locale ? {} : { lang: I18n.locale }
end
```

2019-02-16 08:53 UTC, dniman commented on app/controllers/application_controller.rb
> +  def default_url_options(options={ lang: I18n.locale })
А, понял. Я про файл ~. Работаю в vim, бывает иногда под конец рабочего дня уже все комбинации забываются)))

2019-02-16 09:27 UTC, dniman commented on app/controllers/application_controller.rb
> +  def default_url_options(options={ lang: I18n.locale })
Не могу найти файл ~ . В попытках найти и удалить его удалил файлы файловой системы((
Которые как я понял не восстановить...Блин

2019-02-16 20:14 UTC, dniman commented
>а если тебе передали локаль языка, который не поддерживается у тебя в приложении?
Это же есть

2019-02-16 23:26 UTC, psylone approved these changes

2019-02-16 23:26 UTC, psylone commented on ~
> +    respond_with resource, location: after_sign_in_path_for(resource)
Здесь достаточно установить флэш сообщение и вызвать `super`.

2019-02-18 07:52 UTC, dniman commented on ~
> +    respond_with resource, location: after_sign_in_path_for(resource)
Не работает таким образом. Я параметр передаю first_name

2019-02-18 07:52 UTC, merged