Branch2
dniman/test_guru pull request #2
Opened 2018-11-09 19:08 UTC by dniman

2018-11-10 06:23 UTC, BubuntuClu requested changes

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109183409_create_tests.rb
> +      t.references :category, null: false
внешний ключ еще бы добавить

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109184735_create_questions.rb
> +      t.references :test, null: false
внешний ключ еще бы добавить

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109185148_create_answers.rb
> +      t.references :question, null: false
внешний ключ еще бы добавить

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109190124_create_users.rb
> +      t.integer :is_admin, default: 0
логические поля лучше делать типом `boolean`, они будут иметь значение `true/false`

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109185148_create_answers.rb
> +      t.integer :correct, default: 0
это поле лучше сделать `boolean`

2018-11-10 06:23 UTC, BubuntuClu commented on db/migrate/20181109184735_create_questions.rb
> +      t.string :body, null: false
чит небольшой, что ты все при создании указал. так ты не посмотрел на миграции изменения/добавление свойств в таблицы

2018-11-10 10:44 UTC, dniman commented
разве t.references не добавляет внешний ключ?

2018-11-11 07:33 UTC, BubuntuClu approved these changes

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110094857_create_tests.rb
> +      t.integer :category_id
было правильно. `t.references` добавляет индекс на столбец, он нужен для связей. просто надо было `foreign_key: true` добавить

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110095530_create_answers.rb
> -      t.references :question, null: false
а связь с вопросом куда ушла? она нужна для ответов

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110101353_change_answers_add_question_id.rb
> +      t.integer :question_id
не, так не стоит делать. много миграций это не очень хорошо

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110101703_add_default_values.rb
> +    change_column_default(:tests, :level, 0)
хорошо

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110102429_set_not_null_columns.rb
> +    change_column :categories, :title, :string, null: false
`change_column_null :my_models, :date_column, false`
лучше менять только ограничения, вдруг ты тип данных поменяешь на неподходящий

2018-11-11 07:33 UTC, BubuntuClu commented on db/migrate/20181110103346_add_foreign_keys.rb
> +    add_foreign_key :tests, :categories
это тоже при создании таблицы задавать

2018-11-11 13:04 UTC, merged