Branch3
dniman/test_guru pull request #3
Opened 2018-11-13 20:18 UTC by dniman

2018-11-14 08:46 UTC, BubuntuClu requested changes

2018-11-14 08:46 UTC, BubuntuClu commented on app/models/test.rb
> +    self.joins(:category).where("categories.title = ?", category_title).order("tests.title desc").pluck("tests.title")
`self.` тут можно опустить.

2018-11-14 08:46 UTC, BubuntuClu commented on db/migrate/20181113175609_create_user_answers.rb
> +      t.references :answer, index: true, foreign_key: { to_table: :answers }, null: false
надо связь сделать не через ответы, а через тесты.

2018-11-14 08:46 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.distinct.joins(questions: [:answers]).where("tests.level = ?", level)
через таблицу `users_tests` тут будет запрос. сейчас ты усложнил себе жизнь

2018-11-14 08:46 UTC, BubuntuClu commented on app/models/answer.rb
> +  belongs_to :user
связи с юзером не надо. мы не отслеживаем, кто создал ответ. а если хочешь делать кто отвечал на вопросы, то это неправильная ассоциация

2018-11-14 08:46 UTC, BubuntuClu commented on db/seeds.rb
> +tests = Test.create([{ title: 'Test 1', level: 0, category_id: categories.first.id },
раз ты добавил ассоциации, можно просто `category: categories[0]`

2018-11-15 07:24 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where("tests.level = ?", level)
хорошо, но можно еще проще `tests.where(level: level)`

2018-11-15 07:24 UTC, BubuntuClu commented on app/models/user.rb
>    def user_tests(level)
имя метода, наверное, стоит изменить. у тебя вызов сейчас такой `user.user_tests(level)`. согласись, некрасиво выглядит немного. как на счет `user.tests_by(level)`?

2018-11-15 10:14 UTC, psylone approved these changes

2018-11-15 10:14 UTC, psylone commented on app/models/test.rb
> +    joins(:category).where("categories.title = ?", category_title).order("tests.title desc").pluck("tests.title")
```suggestion
    where(categories: { title: category_title })
```

2018-11-15 15:28 UTC, merged