Branch5
dniman/test_guru pull request #5
Opened 2018-11-19 20:05 UTC by dniman

2018-11-20 08:12 UTC, BubuntuClu requested changes

2018-11-20 08:12 UTC, BubuntuClu commented on app/models/answer.rb
> +  scope :right_answers, -> { where(correct: true) }
`answer.right_answers`. странно выглядит. предлагаю подумать еще над неймингом скоупа

2018-11-20 08:12 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_answers
таким образом мы не сможем никогда создать вопрос без ответов.
и смотри, мы можем пойти со стороны ответов. у нас есть вопрос(допустим он уже был создан). и мы можем делать `Answer.create(title:.., question: qiestion)`. Ответ будет создаваться для вопроса

тут надо подойти со стороны ответов. при создании ответа проверять как дела обстоят у вопроса

2018-11-20 08:12 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
можно валидацию `title` объединить в одну
`validates :title, presence: true, uniqueness: { scope: :level }`

если не хочешь, то валидации для одного поля лучше держать рядом. чтоб не бегать по коду и не искать

2018-11-20 08:12 UTC, BubuntuClu commented on app/models/test.rb
>      joins(:category).where(categories: { title: category_title }).order("tests.title desc").pluck("tests.title")
скоуп должен возвращать объект `ActiveRecord::Relation`, чтобы мы могли делать цепочку вызовов.
так же это уникальный метод твоей модели, сортировка а разных частях системы может потребоваться разная.
надо сортировку и плак вынести из скоупа

оставь метод, просто замени часть на вызов скоупа

2018-11-20 18:09 UTC, BubuntuClu requested changes

2018-11-20 18:09 UTC, BubuntuClu commented on app/models/answer.rb
> +  scope :question_answers, ->(question) { where(question: question) }
тебе не нужен скоуп, у тебя есть ассоциация `belongs_to`, она делает тоже самое

2018-11-20 18:09 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :order_by, ->(attr, direction) { order("tests.#{attr} #{direction}") }
это излишне, зачем нам этот скоуп, если эти аргументы можем подставить напрямую в сортировку или плак?

у тебя должен быть скоуп, который по категории возвращает тесты, и потом ты к результату этого скоупа применяешь сортировку и плак. тебе нужно 14 строчку и 20 подправить в этом файле и все будет хорошо. ну и лишнее все убрать

2018-11-21 08:39 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:answers, "too little") if answer_count < 1
`question.answers.size`
привыкай к ассоциациям

2018-11-21 08:39 UTC, BubuntuClu commented on app/models/answer.rb
> +  def answer_count
это не надо

2018-11-21 18:10 UTC, BubuntuClu commented on app/models/answer.rb
> +    question.answers.size
этот метод не нужен. он никакой логики ведь не делает. ты просто возвращаешь количество ответов для вопроса

2018-11-21 18:28 UTC, psylone approved these changes

2018-11-21 18:28 UTC, psylone commented on app/models/answer.rb
> +  scope :correct_records, -> { where(correct: true) }
Лучше назвать просто `correct`.

2018-11-21 18:28 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:answers, "too little") if answer_count < 1
Что-то я сомневаюсь что этот случай будет иметь место.

2018-11-21 18:28 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:answers, "too much") if answer_count > 4
Если уже есть 4 ответа `4 > 4` вернет `false` и будет создан 5-й ответ.

2018-11-21 18:28 UTC, psylone commented on app/models/test.rb
> +  HIGH_DIFFICULTY = 5..Float::INFINITY
👍

2018-11-21 18:28 UTC, psylone commented on app/models/test.rb
> +  scope :category_tests, ->(title) { joins(:category).where("categories.title = ?", title) }
```suggestion
  scope :category_tests, ->(title) { joins(:category).where(categories: { title: title }) }
```

2018-11-23 16:51 UTC, merged