Branch6
dniman/test_guru pull request #6
Opened 2018-11-28 11:10 UTC by dniman

2018-11-28 19:41 UTC, BubuntuClu requested changes

2018-11-28 19:41 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
тебе могут не поступить параметры, и тогда вопрос не будет создан.
нужно сделать проверку что у тебя вопрос сохранился, при успехе вернуть вопрос, а при провале сообщение об ошибке

2018-11-28 19:41 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render plain: "Question was deleted"
вопрос то ты не удаляешь. просто сообщение выводишь

2018-11-28 19:41 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def parameters
зачем этот метод? ты же можешь напрямую использовать `params`

2018-11-28 19:41 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/tests/1/questions" method="post">
у тебя захардкожен id теста, а вдруг у нас нет теста с первым id?
надо брать значение из `params`

2018-11-29 19:50 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body).merge!(params.permit(:test_id))
`params.require(:question).permit(:body)`
тест тебе не надо сюда мержить. ты вопрос будешь создавать относительно найденного теста и эта связь автоматически проставиться

2018-11-29 19:50 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
`Question.create(question_params)` уже сохораняет вопрос, а ты потом еще раз его сохранешь. не так тут надо поступить

```
question = @test.question.new(question_params)
if question.save
  ...
else
  ...
end
```

2018-11-30 20:17 UTC, psylone approved these changes

2018-12-02 09:23 UTC, merged