Branch9
dniman/test_guru pull request #9
Opened 2018-12-17 21:50 UTC by dniman

2018-12-18 09:01 UTC, BubuntuClu requested changes

2018-12-18 09:01 UTC, BubuntuClu commented on 1
> +class UsersController < ApplicationController
что это за файл?

2018-12-18 09:01 UTC, BubuntuClu commented on :w!
> +class AnswersController < ApplicationController
а это что за файл?

2018-12-18 09:01 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if cookies[:current_path]
`redirect_to cookies[:current_path] || tests_path`

2018-12-18 09:01 UTC, BubuntuClu commented on app/views/shared/_header.html.erb
> +      <p class="nav user">Welcome, <b><%= current_user.email %></b> Guru
`current_user.name` лучше имя выводить

2018-12-18 09:01 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
проверки уникальности нет

2018-12-18 09:01 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!, except: :index
в методе `start` надо использовать текущего пользователя

2018-12-18 12:56 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
это можно в одну строку все прописать. так же если ты добавляешь уникальность в модель, то надо индекс в БД добавить тоже

2018-12-19 10:42 UTC, psylone approved these changes

2018-12-19 10:42 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      cookies[:email] = current_user&.email
Зачем добавлять `email` в куки? У нас доступен объект `current_user`. Также в безопасном вызове `&.` тоже нет необходимости, поскольку в эту ветку условного оператора мы попадем только если пользователь успешно авторизовался.

2018-12-19 10:42 UTC, psylone commented on app/helpers/application_helper.rb
> +    EXCEPT_AUTH_PAGES.each(&:current_page?)
`each` возвращает массив у которого вызывается, в данном случае вернется `EXCEPT_AUTH_PAGES`.

2018-12-19 10:42 UTC, psylone commented on app/helpers/application_helper.rb
> +    EXCEPT_AUTH_PAGES.each(&:current_page?)
`current_page?` будет вызываться у каждого элемента коллекции, то есть у символа, а у символа метода `current_page?` нет.

2018-12-19 10:42 UTC, psylone commented on app/helpers/application_helper.rb
> +    content_tag(:p, flash[type], class: "flash #{type}") if flash.now[type]
Будет здорово выводить все доступные на данный момент флэш сообщения.

2018-12-19 10:42 UTC, psylone commented on app/views/shared/_header.html.erb
> +  <% unless current_page?(login_path) || current_page?(signup_path) %>
Здесь лучше использовать единственный хэлпер и уже внутри него определять на какой странице находимся.

2018-12-19 10:42 UTC, psylone commented on app/views/sessions/_form.html.erb
> +  <%= flash_message(:alert) %>
Удобно флэш сообщения выводить в главном шаблоне приложения, чтобы пользователи видели уведомления всегда в едином месте.

2018-12-19 10:44 UTC, psylone commented on app/helpers/application_helper.rb
> +    EXCEPT_AUTH_PAGES.each(&:current_page?)
Где используется этот метод?

2018-12-20 08:11 UTC, dniman commented on app/controllers/sessions_controller.rb
> +      cookies[:email] = current_user&.email
В скринкасте было.

2018-12-21 21:58 UTC, dniman commented on app/helpers/application_helper.rb
> +    content_tag(:p, flash[type], class: "flash #{type}") if flash.now[type]
Мне не понятно, что тут нужно сделать

2018-12-22 07:06 UTC, merged